### ISSUE TITLE
Authentication model changed

### ISSUE THREAD

**Issue by toralux** [kanekotic/endomondo-unofficial-api#6]
This package is in version 1.0.87 broken.

Looks like Endomondo have changed it's authentication model and removed the field secureToken so lib/authentication.js will fail on line 22. Please test and see if this is for all users.

**Comment by toralux** [comment]
Added pull request to fix this issue:
https://github.com/kanekotic/endomondo-unofficial-api/pull/7

**Comment by toralux** [comment]
Anyway, still one test failing that has to be sorted out:

integration should › can authenticate and retrieve data
Required parameter 'email' not present for app with User-Agent: null

**Comment by alvarolorentedev** [comment]
hello @toralux thanks for the PR. I will have a look this weekend and also try to fix that test :)

**Comment by toralux** [comment]
@kanekotic Did you have a look at my PR (https://github.com/kanekotic/endomondo-unofficial-api/pull/7) or didn't you encounter any issues with the old version (as I did)?

**Comment by alvarolorentedev** [comment]
Thank you for your patience  Merged.
